apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        securityContext:
          privileged: true
