apiVersion: v1
kind: Service
metadata:
  name: toolbox-container
spec:
  selector:
    app: toolbox-container
  ports:
  - name: http-80
    port: 80
    protocol: TCP
  - name: http-8080
    port: 8080
    protocol: TCP
  - name: https-443
    port: 443
    protocol: TCP
  - name: https-8443
    port: 8443
    protocol: TCP
  - name: ssh
    port: 22
    protocol: TCP
  type: ClusterIP
