apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        volumeMounts:
        - name: home
          mountPath: /home/toolbox
      volumes:
      - name: home
        persistentVolumeClaim:
          claimName: toolbox-container-home
