apiVersion: apps/v1
kind: Deployment
metadata:
  name: toolbox-container
spec:
  template:
    spec:
      containers:
      - name: toolbox-container
        volumeMounts:
        - name: host
          mountPath: /host
          mountPropagation: Bidirectional
      volumes:
      - name: host
        hostPath:
          path: /
