apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    reloader.stakater.com/match: "true"
  name: toolbox-container-init
data:
  init.sh: |
    #!/bin/bash

    echo Hello from the custom init script!
    echo CHECKPOINT1
    echo CHECKPOINT2
    echo CHECKPOINT3
    echo CHECKPOINT4
